---
title: MSSQLSERVER_8680 | Microsoft Docs
ms.custom: ''
ms.date: 04/04/2017
ms.prod: sql
ms.reviewer: ''
ms.suite: sql
ms.technology: supportability
ms.tgt_pltfrm: ''
ms.topic: language-reference
helpviewer_keywords:
- 8680 (Database Engine error)
ms.assetid: 79f7270e-e4df-4f4e-bc78-2dcad6a9f140
caps.latest.revision: 13
author: MashaMSFT
ms.author: mathoma
manager: craigg
ms.openlocfilehash: b2b2f18b2a3505dd8e76545c9df337fd61a81d0c
ms.sourcegitcommit: ee661730fb695774b9c483c3dd0a6c314e17ddf8
ms.translationtype: HT
ms.contentlocale: es-ES
ms.lasthandoff: 05/19/2018
ms.locfileid: "34326026"
---
# <a name="mssqlserver8680"></a>MSSQLSERVER_8680
[!INCLUDE[appliesto-ss-xxxx-xxxx-xxx-md](../../includes/appliesto-ss-xxxx-xxxx-xxx-md.md)]
  
## <a name="details"></a>Detalles  
  
|||  
|-|-|  
|Nombre del producto|SQL Server|  
|Identificador del evento|8680|  
|Origen del evento|MSSQLSERVER|  
|Componente|SQLEngine|  
|Nombre simbólico|REMOTE_ERR|  
|Texto del mensaje|Error interno del procesador de consultas: error inesperado al procesar una fase de consulta remota.|  
  
## <a name="explanation"></a>Explicación  
Se ha producido un error interno al procesar la consulta.  
  
## <a name="user-action"></a>Acción del usuario  
Póngase en contacto con el servicio de soporte técnico y atención al cliente de Microsoft (CSS). Tenga a mano la descripción del error, los seguimientos y los volcados (si dispone de ellos).  
  
